%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Matlab code For Dummies %
% TD SLI 2 - Sujet n°5    %
%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all; close all;

% Déclaration des modèles "fonction de transfert" et forme compagne commande 

TF_y_u = tf(...

Ac = [...
Bc = [...
Cc = [...
Dc = [...

EE1_y_u = ss(...


vp_EE1 = eig(...                 % valeurs propres

% Commandabilité & Observabilité

rank(ctrb(...
rank(obsv(...

% Conception d'une commande par retour d'état (Question 2)
vp_EE1_asservi = [...

K = acker(...

% Conception d'un observateur-estimateur identité (Question 3)
vp_EE1_obs_ident = [...

G = acker(...

F = ...

H = ...


% Conception d'un observateur-estimateur minimal (hors exercice)
vp_EE1_obs_mini = [...

G2 = acker(...

Fm = ...

Gm = ...

Hm = ...


% Ecriture du système composite {Système + commande + observateur identité}
% Question 4

Acomp = [...

Bcomp = [...

Ccomp = [...

Dcomp = zeros(...

sys_comp = ss(...

% Ecriture des FT du système composite + Verif propriétés ctrb et obsv
% Question 5

TF_sys_comp = zpk(tf(...

rank(ctrb(...

rank(obsv(...


% Utilisation d'une matrice de passage P pour trouver une EE composite par
% bloc - illustration du principe de séparation (Questions 6 ->9)

P = [...
inverse_P = inv(...

sys_comp_bloc = ss(...

rank(ctrb(...

rank(obsv(...

TF_sys_comp = zpk(tf(...